### ISSUE TITLE
Error with 2 levels clusters

### ISSUE THREAD

**Issue by yannk-lm** [phipsonlab/speckle_old#2] opened 2022-05-25 17:11 UTC
Hello,

Thank you for this useful package.

When I provide a vector with 2 levels for the clusters argument in the `propeller` function, I get the following error :
`Error in tmixture.matrix(out$t, stdev.unscaled, df.total, proportion,  : 
  Dims of tstat and stdev.unscaled don't match`

Is it not possible to find differences of proportions when we only have 2 levels of cluster ?

FYI, I don't have any issue when the clusters argument has more than 2 levels and my study is based on the differences between 2 groups.

Thank you for your help.

Regards,
Yannick

**Comment by bphipson** [comment] 2022-05-25 23:47
Thanks for bringing this to my attention. Can you provide the code that you used that produced an error please? Propeller should work for only 2 clusters, but I will debug and see where it is going wrong.

**Comment by yannk-lm** [comment] 2022-05-26 07:59
Thank you for your answer.
I've made a reproductible example that end up with the same error : 

`seed(0)`
`clusters <- sample(1:2, size = 2000, replace = TRUE)`
`seed(0)`
`sample <- sample(c("A","B","C","D","E"), size = 2000, replace = TRUE)`
`group <- ifelse(sample %in% c("A","B"),"Grp1","Grp2")`
`speckle::propeller(clusters = clusters, sample = sample, group = group)`

I hope this will help.

Regards,
Yannick

**Comment by bphipson** [comment] 2022-05-30 03:46
Hi Yannick

Thank you for providing the reproducible example. I found the bug in the code, I will push a fix for this today. If you have any other issues please let me know. I think the two cell type scenario is quite interesting because if one cell type changes, then the other will also change.

Cheers,
Belinda

**Comment by yannk-lm** [comment] 2022-05-30 07:59
Hello Belinda,

Thank you very much and I don't have any other issues.

Regards,
Yannick

**Comment by bphipson** [comment] 2022-05-31 00:40
bug fixed for using propeller when there are only 2 cell types present in the single cell data.

**Closed as completed** 2022-05-31 00:39 UTC
